version: '3'

services:
  my_app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rackup config.ru -E development --host 0.0.0.0 -p 8000 
    environment:
      POSTGRES_DB: blog
      POSTGRES_HOST: my_app_db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend

networks: 
  backend:
    driver: bridge
    
volumes:
  pg-data: